"""empty message

Revision ID: 6ca16dd53864
Revises: 3d0c43f03396
Create Date: 2020-11-26 00:24:28.583332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ca16dd53864'
down_revision = '3d0c43f03396'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('customer_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'orders', 'customers', ['customer_id'], ['id'])
    op.add_column('shipments', sa.Column('order_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'shipments', 'orders', ['order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shipments', type_='foreignkey')
    op.drop_column('shipments', 'order_id')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'customer_id')
    # ### end Alembic commands ###
