"""empty message

Revision ID: 752cf9a1b52c
Revises: 6ca16dd53864
Create Date: 2020-11-26 17:26:56.823966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '752cf9a1b52c'
down_revision = '6ca16dd53864'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipments', sa.Column('supplier_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'shipments', 'suppliers', ['supplier_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shipments', type_='foreignkey')
    op.drop_column('shipments', 'supplier_id')
    # ### end Alembic commands ###
