"""empty message

Revision ID: bdfa0ba03bcc
Revises: 752cf9a1b52c
Create Date: 2020-12-06 21:02:53.702263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdfa0ba03bcc'
down_revision = '752cf9a1b52c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suppliers', 'products')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suppliers', sa.Column('products', sa.BLOB(), nullable=True))
    # ### end Alembic commands ###
